# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urlInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.URLField(max_length=500)),
                ('expanded', models.URLField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
