# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlexp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlinfo',
            name='waybackTime',
            field=models.CharField(default='No available snapshot of this url on Wayback', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlinfo',
            name='waybackUrl',
            field=models.CharField(default='No available snapshot of this url on Wayback', max_length=500),
            preserve_default=False,
        ),
    ]
